name: Build Wheel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Set to false to prevent one job failure from cancelling other job.
      matrix:
        os: [windows-2019]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"] # Update to the Python versions you want to use
        arch: [x86_64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: python -m pip install --upgrade pip setuptools wheel Cython mido numpy scipy

    - name: Build wheel for madmom
      run: |
        mkdir dist
        pip wheel git+https://github.com/CPJKU/madmom.git -w dist

    - name: Print files in dist
      run: |
        ls dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.arch }}
        path: ./dist/*.whl
